apiVersion: v1
kind: Service
metadata:
  name: xplainai-api
  labels:
    app.kubernetes.io/name: xplainai-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: xplainai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xplainai-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
